### ISSUE TITLE
Multiclassing

### ISSUE THREAD

**Issue by Arnoldave** [5e-bits/5e-srd-api#197]
There's a bit of extra data to be accounted for in regards to multi-classing. Specifically, I'm thinking of the ability score prerequisites, and the reduced set of starting proficiencies. Would be happy to have a crack at this myself, though on request, I'm opening this issue first to discuss the problem.

**Comment by fergcb** [comment]
Is this more of an issue for the database repo? It would presumably involve modifying Class documents, rather than changing anything in the API code? Or did you have another solution in mind?

**Comment by Arnoldave** [comment]
Fair point. Had a bit of a dementia moment, and plonked it in here without thinking. That being said, there will be some small changes that get put into this repo, so it will be relevant here.

**Comment by fergcb** [comment]
Changes such as what? I'm assuming updating the docs, but what else? A specific `/api/classes/${index}/multiclassing` endpoint? I'm just trying to ascertain your proposed solution.

**Comment by Arnoldave** [comment]
Mainly updating the docs, and the schema models. Since it's a 1 to 1 relationship, it's probably best just to be implemented as an extra object property for the Class model.

**Comment by bagelbits** [comment]
These are now in the DB and API
