### ISSUE TITLE
Class Multiple Starting Equipment Options

### ISSUE THREAD

**Issue by GeraldTo** [5e-bits/5e-srd-api#214]
When there are multiple items for an individual option it is displayed as a object with attributes representing an index instead of using an array. The database uses an array so it doesn't line up. For example in classes/fighter under starting_equipment_options[0].from[1] the option is:
```json
{
  "0": {
    "equipment": {                  
      "index": "leather",
      "name": "Leather",
      "url": "/api/equipment/leather"
    },
    "quantity": 1
  },
  "1": {
    "equipment": {
      "index": "longbow",
      "name": "Longbow",
      "url": "/api/equipment/longbow"
    },
    "quantity": 1
  },
  "2": {
    "equipment": {
      "index": "arrow",
      "name": "Arrow",
      "url": "/api/equipment/arrow"
    },
    "quantity": 20
    }
}
```
This should be an array

**Comment by bagelbits** [comment]
I can confirm that it is doing that. I suspect something has changed in how MongoDB Atlas is returning data to the server. Since it looks like this in the DB itself:
![image](https://user-images.githubusercontent.com/353626/120248309-71967480-c22b-11eb-8911-69d4f0fea32a.png)

**Comment by bagelbits** [comment]
I'm going to redeploy the database again to see if that kicks something loose.

**Comment by bagelbits** [comment]
Nope. I suspect that something doesn't like an array of objects and arrays. I wonder if it's the web rendering. @GeraldTo Do you have issues treating it like an array when you're writing code against it?

**Comment by GeraldTo** [comment]
It basically acts like an object, not an array. I don't have issues with other arrays so it's just this

**Comment by bagelbits** [comment]
I bet this is the same issue as #240

**Comment by bagelbits** [comment]
I think this is resolved now? Feel free to reopen if it isn't.
