### ISSUE TITLE
Increase GraphQL discoverability

### ISSUE THREAD

**Issue by bagelbits** [5e-bits/5e-srd-api#222]
Currently, GraphQL endpoint is word of mouth. There should be an easy way to find it on the front page as well as some documentation for common things like sort and filter.

**Comment by tpolito** [comment]
There is a section in the [documentation for graphql.](https://www.dnd5eapi.co/docs/#graphql)

**Comment by bagelbits** [comment]
Ironically, I definitely wrote that and forgot. But good thing that's in there. I can add some more on sorting and filtering too.
