### ISSUE TITLE
5e-SRD-StartingEquipment.json still present in DB

### ISSUE THREAD

**Issue by Wyzards** [5e-bits/5e-srd-api#228]
5e-SRD-StartingEquipment.json is still present within the database. Its information is now contained within each individual class, and it should be removed. The API needs some updating to make sure this removal goes smoothly, but that's too far out of my element.

Relevant discord discussion: https://discord.com/channels/656547667601653787/656547667601653790/866165321824206888

Enjoy!

**Comment by bagelbits** [comment]
This has now been removed.
