### ISSUE TITLE
Equipment Category Array Wrapping

### ISSUE THREAD

**Issue by Wyzards** [5e-bits/5e-srd-api#240]
I'm doing some work with starting-equipment and I've noticed an issue.

In the starting-equipment-options for Cleric, this is one of the Choices.
```
{
      "choose": 1,
      "type": "equipment",
      "from": [
        {
          "equipment_category": {
            "index": "holy-symbols",
            "name": "Holy Symbols",
            "url": "/api/equipment-categories/holy-symbols"
          }
        }
      ]
    }

```
You'll note that there's an issue here, as from attribute is an array, despite it pointing to an equipment category. For all other choices from an equipment category, the format is as follows
```
"from": {
  "equipment_category": {
    "index": "holy-symbols",
    "name": "Holy Symbols",
    "url": "/api/equipment-categories/holy-symbols"
  }
}
```

This is actually how it is listed within the 5e-SRD-Classes.json file in the database, but for whatever reason when it's requested via the API it wraps it in an array, which causes issues.

This occurs for the following cases:
- Cleric's Holy Symbol
- Druid's Druidic Focus
- Paladin's Holy Symbol
- Warlock's simple weapon choice

In that sense, it'd seem that whenever the top-level choice is from an equipment-category, this occurs. All other occurrences where a choice is from an equipment category, it's not wrapped in this array, so it makes sense to remove it. In the models file, StartingEquipmentOptions `from` attribute has a type of [StartingEquipmentOption], so essentially it's forcing the data to output as an array even when it doesn't need to be.

**Comment by bagelbits** [comment]
Now that choice reform has landed, I'm going to resolve this.
