### ISSUE TITLE
A little confusion with the return value for Monster/Action

### ISSUE THREAD

**Issue by jesshmusic** [5e-bits/5e-srd-api#243]
https://github.com/5e-bits/5e-srd-api/blob/8e0eefededbf09e9ab6ffd9f5d3450d1c0da27b2/src/models/monster.js#L10-L15

So for this I am only ever expecting an array of `ActionDamage`

But when I hit the `api/monsters/veteran` endpoint, I am getting what looks like a `Choice` object. This is cool, and very likely I am not understanding GraphQL (trying to parse the data in Rails), but how is this being implemented in your code? haha. It seems a mystery to me.

I see this:
```
"damage": [
        {
          "choose": 1,
          "type": "damage",
          "from": [
            {
              "damage_type": {
                "index": "slashing",
                "name": "Slashing",
                "url": "/api/damage-types/slashing"
              },
              "damage_dice": "1d8+3"
            },
            {
              "damage_type": {
                "index": "thunder",
                "name": "Thunder",
                "url": "/api/damage-types/thunder"
              },
              "damage_dice": "1d10+3"
            }
          ]
        }
      ]
```

**Comment by bagelbits** [comment]
Not well. I think that needs to be updated to support multiple types:

https://github.com/Automattic/mongoose/issues/4929#issuecomment-276249592

**Comment by bagelbits** [comment]
The models file and types have been updated to fully match the shape to expect. I think this should be resolved now? Feel free to reopen if it is not.
