### ISSUE TITLE
Mountain dwarf is missing

### ISSUE THREAD

**Issue by SvenLie** [5e-bits/5e-srd-api#249]
Hey,

the subrace mountain dwarf is missing. Can u add that?

**Comment by fergcb** [comment]
Thanks for the suggestion! Unfortunately, we're not legally allowed to distribute content that isn't included in the D&D 5e SRD. The SRD only contains one subrace per full race. In this case, the only dwarf subrace is the Hill Dwarf.

### What is the SRD?

The SRD, or Systems Reference Document, contains guidelines for publishing content under the OGL. This allows for some of the data for D&D 5e to be open source. The API only covers data that can be found in the SRD. You can find it here:
 [https://media.wizards.com/2016/downloads/DND/SRD-OGL_V5.1.pdf](https://media.wizards.com/2016/downloads/DND/SRD-OGL_V5.1.pdf)

This reddit post is a good explanation of how this works:
https://www.reddit.com/r/DnD/comments/hqw3jx/til_that_the_spell_tashas_hideous_laughter_was/fy0q5ej/
