### ISSUE TITLE
Harvesting Information for Monsters

### ISSUE THREAD

**Issue by mrchainman** [5e-bits/5e-srd-api#257]
Hi,
First of l thanks for this awesome project.
I think it would be really cool, if the one could also query for Harvesting Information for each monster.
The HHH has all the needed Information.

If there is help needed I can gather the Information and give it to you in tje required format.

Thanks

**Comment by bagelbits** [comment]
Unless that's covered under the Open Gaming License (which I'm going to take a guess that it isn't), we won't be able to add it to the API. However, you're welcome to fork either the DB or API to put that data in yourself.
