### ISSUE TITLE
/api/levels endpoint returned by /api is not found

### ISSUE THREAD

**Issue by drmason13** [5e-bits/5e-srd-api#304]
When getting the root /api endpoint I get a response object that includes:
```
levels: "/api/levels",
```
but calling that url returns a 404:
```bash
$ curl https://www.dnd5eapi.co/api/levels
{"error":"Not found"}
```

I'm not sure if this is a mistake in the /api root response or the an actual missing /api/levels endpoint, but the example response _doesn't_ include levels.

I'd expect either the endpoint to not be listed or for it to exist.
I expect it's gotten mixed up with `/api/classes/{index}/levels` somehow.

BTW, thank you so much for this API! I'm very impressed by the documentation overall. It's well laid out and very approachable.

**Comment by bagelbits** [comment]
Whoops! The downside of automating this endpoint. 😅
