### ISSUE TITLE
Filter Monsters by XP and XP Range

### ISSUE THREAD

**Issue by Devcon324** [5e-bits/5e-srd-api#318]
Currently cannot filter monsters by XP (ex. https://www.dnd5eapi.co/api/monsters?xp=_____)

**Rationale:**
Although Challenge Rating (CR) maps to XP (https://makeaskillcheck.com/5e-how-does-cr-work/), there is an exception for CR0 monsters with 0xp or 10xp. 

Additionally in some circumstances, searching for monsters via XP is a more direct approach to finding monsters that scale with difficulty based on the party level or size where an algorithm requires XP values to provide an acceptable XP range.

**Example:** 
https://www.dndbeyond.com/sources/basic-rules/building-combat-encounters 
The problem becomes complicated when you want more than 1 monster. 
If we want 3 monsters, we must find 3 monsters who's sum of XP is within the party XP threshold. 
This is challenging because if you want any monsters from CR0 and upwards, you need to convert the convert your XP threshold range to a CR range before searching the API, then convert each selected monsters CR back to XP to follow the D&D Beyond algorithm.

Hope this makes sense. I am not sure how to approach this but If someone would like to work together on this, I would love to learn and contribute.

**Comment by bagelbits** [comment]
This is technically already supported with the GraphQL endpoint. I added that end point to avoid adding things like this. 😅

If you were to do this, you would want something similar to what I did with CR, given that there is almost a direct 1:1 mapping of XP to CR. CR0 being the only exception and I think the distinguishing factor there is if it has an attack or not.
