### ISSUE TITLE
GraphQl Search Functionality

### ISSUE THREAD

**Issue by stonefarmer9** [5e-bits/5e-srd-api#324]
Currently the GraphQL endpoint only accepts fully formed fields for filter queries. 

It would be great if the endpoint could be extended to allow the passing of free text strings and return results containing that string. 

E.G A search query for all monsters whose name contains 'gon'

**Comment by abias1122** [comment]
There should be something like what you want now. Try using one of the queries with the `name` parameter and see if it works the way you want it to.
