### ISSUE TITLE
path in quotes in bundled yaml when path contain curly braces

### ISSUE THREAD

**Issue by jarjav** [5e-bits/5e-srd-api#354]
in path I have reference to external file. path name contain {id} 
`paths:
  /v1/feedback/poll/answer/input-types/{id}:
    $ref: "./v1/paths/pollAnswerInputTypesId.yaml"`
when i run 
`swagger-cli bundle -r input.yaml -o output.yaml -t yaml`
bundled output.yaml path is in quotes and swagger-ui does not show this path
`paths:
'/v1/feedback/poll/answer/input-types/{feedbackPollAnswerInputTypeId}'`
how to generate bundled yaml with same path value? (not in quotes)

regards

**Comment by bagelbits** [comment]
Are you sure you're asking this on the correct repo? I don't think this is related to the D&D API.
