### ISSUE TITLE
[Feature Request] Add Search API

### ISSUE THREAD

**Issue by pjp94** [5e-bits/5e-srd-api#374]
It would be really useful to have a search endpoint we could call to get results with urls in order to support client-side searching without having to fetch and store the data from every single endpoint ahead of time.

A suggestion has been made in the Discord to use [MongoDB Atlas Search](https://www.mongodb.com/docs/atlas/atlas-search/) to support this.

> We’d have to add a search index and a new rest endpoint with some input sanitization and limits but could be a nice feature! 
> graphql does provide a bit of this in a pretty nice way, so you could almost design an api client to wrap the graphql api a bit and offer search functionality lite.

**Comment by bagelbits** [comment]
Does the GraphQL endpoint not do this for you?

**Comment by fergcb** [comment]
> That would only work if you enter an exact match to a GraphQL argument right? For instance, if I want to search for a Gnoll and I type "gno", I wouldn't be able to utilize GraphQL to get the information.

The GraphQL `name` filter on `monsters` does return partial matches - "gno" returns Gnoll and Deep Gnome.

> And on top of that, how would you know to query the `monster` field?

You could simply query all of the collections you wanted to include in your search results in parallel, and then collate the results client-side. I appreciate that it's not a perfect solution, but it'll get you the functionality you're after, by the sounds of it!
